export const DATABASE_ID = process.env.NEXT_PUBLIC_APPWRITE_DATABASE_ID!;
export const WORKSPACES_ID =
  process.env.NEXT_PUBLIC_APPWRITE_COLLECTION_WORKSPACES_ID!;
export const MEMBERS_ID =
  process.env.NEXT_PUBLIC_APPWRITE_COLLECTION_MEMBERS_ID!;
export const PROJECTS_ID =
  process.env.NEXT_PUBLIC_APPWRITE_COLLECTION_PROJECTS_ID!;
export const IMAGES_BUCKET_ID =
  process.env.NEXT_PUBLIC_APPWRITE_IMAGES_BUCKET_ID!;
